-- Clean Customer Orders Table
  
UPDATE PIZZA_RUNNER.CUSTOMER_ORDERS
SET EXCLUSIONS =
 CASE WHEN EXCLUSIONS LIKE '' OR EXCLUSIONS = 'null'
 THEN NULL
 ELSE EXCLUSIONS
 END

UPDATE PIZZA_RUNNER.CUSTOMER_ORDERS
SET EXTRAS =
 CASE WHEN EXTRAS LIKE '' OR EXTRAS = 'null'
 THEN NULL
 ELSE EXTRAS
 END

-- Clean Runner Orders Table

UPDATE PIZZA_RUNNER.RUNNER_ORDERS
SET PICKUP_TIME = 
 CASE
  WHEN PICKUP_TIME = 'null' THEN NULL
	ELSE PICKUP_TIME
	END;


UPDATE PIZZA_RUNNER.RUNNER_ORDERS
SET DISTANCE = 
 CASE
	WHEN DISTANCE = 'null' THEN NULL
	WHEN DISTANCE LIKE '%km' THEN TRIM('km' from DISTANCE)
	ELSE DISTANCE 
  END;


UPDATE PIZZA_RUNNER.RUNNER_ORDERS
SET DURATION = 
 CASE
  WHEN DURATION = 'null' THEN NULL
  WHEN DURATION LIKE '%mins' THEN TRIM('mins' FROM DURATION) 
  WHEN DURATION LIKE '%minute' THEN TRIM('minute' FROM DURATION)        
  WHEN DURATION LIKE '%minutes' THEN TRIM('minutes' FROM DURATION)
	ELSE DURATION
	END;

UPDATE PIZZA_RUNNER.RUNNER_ORDERS
SET CANCELLATION = 
 CASE
	WHEN CANCELLATION = 'null' OR CANCELLATION LIKE '' THEN NULL
	ELSE CANCELLATION
	END;

  
-- Correct the Data Types

ALTER TABLE PIZZA_RUNNER.RUNNER_ORDERS
ALTER COLUMN PICKUP_TIME TYPE TIMESTAMP USING PICKUP_TIME::TIMESTAMP,
ALTER COLUMN DISTANCE TYPE FLOAT USING DISTANCE::FLOAT,
ALTER COLUMN DURATION TYPE INTEGER USING DURATION::INTEGER
